// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_cIabWqoVk0g0J8VV0MFqJR6ASOID30',
    appId: '1:859622230501:web:a590d28ff7c6632d09870c',
    messagingSenderId: '859622230501',
    projectId: 'punjabigpt',
    authDomain: 'punjabigpt.firebaseapp.com',
    storageBucket: 'punjabigpt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKNnsnL4Mkfq3NOSaPXt2ftdXQlV6kULo',
    appId: '1:859622230501:android:8ff00f1f9d06278109870c',
    messagingSenderId: '859622230501',
    projectId: 'punjabigpt',
    storageBucket: 'punjabigpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZISwnxfqIOVBVBn8wfTYOjX37nLlKw8w',
    appId: '1:859622230501:ios:356d4a3938a02a9a09870c',
    messagingSenderId: '859622230501',
    projectId: 'punjabigpt',
    storageBucket: 'punjabigpt.appspot.com',
    iosBundleId: 'com.example.punjabigpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZISwnxfqIOVBVBn8wfTYOjX37nLlKw8w',
    appId: '1:859622230501:ios:36aa980dbae1e7d109870c',
    messagingSenderId: '859622230501',
    projectId: 'punjabigpt',
    storageBucket: 'punjabigpt.appspot.com',
    iosBundleId: 'com.capstone.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7_cIabWqoVk0g0J8VV0MFqJR6ASOID30',
    appId: '1:859622230501:web:9ef7a39809c4f5fb09870c',
    messagingSenderId: '859622230501',
    projectId: 'punjabigpt',
    authDomain: 'punjabigpt.firebaseapp.com',
    storageBucket: 'punjabigpt.appspot.com',
  );
}
